// <auto-generated />
using System;
using MessApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MessApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260610165029_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MessApi.Models.CommonBill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("BillType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MessId")
                        .HasColumnType("int");

                    b.HasKey("BillId")
                        .HasName("PK__CommonBi__11F2FC6ADCB34CF6");

                    b.HasIndex("MessId");

                    b.ToTable("CommonBills");
                });

            modelBuilder.Entity("MessApi.Models.MarketCost", b =>
                {
                    b.Property<int>("CostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CostId"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime");

                    b.Property<int>("MessId")
                        .HasColumnType("int");

                    b.Property<int>("MessMemberId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("Unit")
                        .HasColumnType("int");

                    b.HasKey("CostId")
                        .HasName("PK__MarketCo__8285233EDABEC44E");

                    b.HasIndex("MessId");

                    b.HasIndex("MessMemberId");

                    b.HasIndex("Unit");

                    b.ToTable("MarketCosts");
                });

            modelBuilder.Entity("MessApi.Models.Meal", b =>
                {
                    b.Property<int>("MealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealId"));

                    b.Property<decimal>("Breakfast")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("Dinner")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("Lunch")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateOnly>("MealDate")
                        .HasColumnType("date");

                    b.Property<int>("MessId")
                        .HasColumnType("int");

                    b.Property<int>("MessMemberId")
                        .HasColumnType("int");

                    b.HasKey("MealId")
                        .HasName("PK__Meals__ACF6A63D4EEB18A2");

                    b.HasIndex("MessMemberId");

                    b.HasIndex(new[] { "MessId", "MessMemberId", "MealDate" }, "UQ__Meals__8A69AE4C9E41CEAE")
                        .IsUnique();

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("MessApi.Models.Mess", b =>
                {
                    b.Property<int>("MessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())", "DF__Mess__CreatedAt__5812160E");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime");

                    b.Property<string>("MessName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime");

                    b.HasKey("MessId")
                        .HasName("PK__Mess__9CC50CDD06C6E9E2");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Mess");
                });

            modelBuilder.Entity("MessApi.Models.MessMember", b =>
                {
                    b.Property<int>("MessMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessMemberId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())", "DF__MessMembe__Joine__5EBF139D");

                    b.Property<int>("MessId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Rent")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Member", "DF__MessMember__Role__5DCAEF64");

                    b.HasKey("MessMemberId")
                        .HasName("PK__MessMemb__2F8CE6B8620BB8A1");

                    b.HasIndex(new[] { "MessId", "Email" }, "UQ__MessMemb__D6581C8FCF77A519")
                        .IsUnique();

                    b.ToTable("MessMembers");
                });

            modelBuilder.Entity("MessApi.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())", "DF__RefreshTo__Creat__3F466844");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__RefreshT__3214EC07B8D56923");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MessApi.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC07FA976C93");

                    b.HasIndex(new[] { "Name" }, "UQ__Roles__737584F6787F58D2")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MessApi.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PK__Unit__3214EC07F0A552C5");

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("MessApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())", "DF__Users__CreatedAt__38996AB5");

                    b.Property<int?>("CurrentMessId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC07148AD525");

                    b.HasIndex("CurrentMessId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534B23CDD0E")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MessApi.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AssignedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UserId", "RoleId")
                        .HasName("PK__UserRole__AF2760AD4B7A5E2E");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("MessManagement.Shared.DTOs.MessDto", b =>
                {
                    b.Property<decimal>("CommonBillPerMember")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("CurrentMess")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCreatedByCurrentUser")
                        .HasColumnType("bit");

                    b.Property<decimal>("MealRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MemberNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MessId")
                        .HasColumnType("int");

                    b.Property<string>("MessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalMarketCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalMeals")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("MessManagement.Shared.DTOs.MessMemberSummaryDto", b =>
                {
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GetOrPayFromMeal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsCreatedByCurrentUser")
                        .HasColumnType("bit");

                    b.Property<decimal>("MarketCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MealRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MessId")
                        .HasColumnType("int");

                    b.Property<int>("MessMemberId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalHaveToPay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalMeal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalMealCost")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("MessApi.Models.CommonBill", b =>
                {
                    b.HasOne("MessApi.Models.Mess", "Mess")
                        .WithMany("CommonBills")
                        .HasForeignKey("MessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__CommonBil__MessI__6E01572D");

                    b.Navigation("Mess");
                });

            modelBuilder.Entity("MessApi.Models.MarketCost", b =>
                {
                    b.HasOne("MessApi.Models.Mess", "Mess")
                        .WithMany("MarketCosts")
                        .HasForeignKey("MessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MarketCosts_Mess");

                    b.HasOne("MessApi.Models.MessMember", "MessMember")
                        .WithMany("MarketCosts")
                        .HasForeignKey("MessMemberId")
                        .IsRequired()
                        .HasConstraintName("FK__MarketCos__MessMemberId__6B24EA82");

                    b.HasOne("MessApi.Models.Unit", "UnitNavigation")
                        .WithMany("MarketCosts")
                        .HasForeignKey("Unit")
                        .HasConstraintName("FK__MarketCos__UnitId__6A30C649");

                    b.Navigation("Mess");

                    b.Navigation("MessMember");

                    b.Navigation("UnitNavigation");
                });

            modelBuilder.Entity("MessApi.Models.Meal", b =>
                {
                    b.HasOne("MessApi.Models.Mess", "Mess")
                        .WithMany("Meals")
                        .HasForeignKey("MessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Meals__MessId__66603565");

                    b.HasOne("MessApi.Models.MessMember", "MessMember")
                        .WithMany("Meals")
                        .HasForeignKey("MessMemberId")
                        .IsRequired()
                        .HasConstraintName("FK__Meals__UserId__6754599E");

                    b.Navigation("Mess");

                    b.Navigation("MessMember");
                });

            modelBuilder.Entity("MessApi.Models.Mess", b =>
                {
                    b.HasOne("MessApi.Models.User", "CreatedByNavigation")
                        .WithMany("Messes")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK__Mess__CreatedBy__59063A47");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("MessApi.Models.MessMember", b =>
                {
                    b.HasOne("MessApi.Models.Mess", "Mess")
                        .WithMany("MessMembers")
                        .HasForeignKey("MessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__MessMembe__MessI__5FB337D6");

                    b.Navigation("Mess");
                });

            modelBuilder.Entity("MessApi.Models.RefreshToken", b =>
                {
                    b.HasOne("MessApi.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MessApi.Models.User", b =>
                {
                    b.HasOne("MessApi.Models.Mess", "CurrentMess")
                        .WithMany("Users")
                        .HasForeignKey("CurrentMessId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Users_Mess");

                    b.Navigation("CurrentMess");
                });

            modelBuilder.Entity("MessApi.Models.UserRole", b =>
                {
                    b.HasOne("MessApi.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UserRoles__RoleI__5441852A");

                    b.HasOne("MessApi.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UserRoles__UserI__534D60F1");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MessApi.Models.Mess", b =>
                {
                    b.Navigation("CommonBills");

                    b.Navigation("MarketCosts");

                    b.Navigation("Meals");

                    b.Navigation("MessMembers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("MessApi.Models.MessMember", b =>
                {
                    b.Navigation("MarketCosts");

                    b.Navigation("Meals");
                });

            modelBuilder.Entity("MessApi.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MessApi.Models.Unit", b =>
                {
                    b.Navigation("MarketCosts");
                });

            modelBuilder.Entity("MessApi.Models.User", b =>
                {
                    b.Navigation("Messes");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
